import os

# Telegram API Credentials (Get from my.telegram.org)
TELEGRAM_API_ID = os.getenv("TELEGRAM_API_ID", "YOUR_TELEGRAM_API_ID")
TELEGRAM_API_HASH = os.getenv("TELEGRAM_API_HASH", "YOUR_TELEGRAM_API_HASH")
TELEGRAM_PHONE_NUMBER = os.getenv("TELEGRAM_PHONE_NUMBER", "YOUR_TELEGRAM_PHONE_NUMBER")
TELEGRAM_GROUP_ID = int(os.getenv("TELEGRAM_GROUP_ID", "-1001234567890"))

# OpenAI API Key
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "YOUR_OPENAI_API_KEY")

# Zerodha Kite API
ZERODHA_API_KEY = os.getenv("ZERODHA_API_KEY", "YOUR_ZERODHA_API_KEY")
ZERODHA_ACCESS_TOKEN = os.getenv("ZERODHA_ACCESS_TOKEN", "YOUR_ZERODHA_ACCESS_TOKEN")
